services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Command to install pgvector
    command: ["bash", "-c", "apt-get update && apt-get install -y postgresql-contrib && su postgres -c 'psql -d mydatabase -c \"CREATE EXTENSION vector;\"'"]


volumes:
  postgres_data:
